DROP TABLE IF EXISTS tickets;

DROP TABLE IF EXISTS films;

DROP TABLE IF EXISTS customers;

CREATE TABLE customers(
id SERIAL8 PRIMARY KEY,
f_name VARCHAR(255),
l_name VARCHAR(255),
funds INT
);

CREATE TABLE films(
id SERIAL8 PRIMARY KEY,
title VARCHAR(255),
price INT
);

CREATE TABLE tickets(
id SERIAL8 PRIMARY KEY,
film_id INT8 REFERENCES films(id) ON DELETE CASCADE,
customer_id INT8 REFERENCES customers(id) ON DELETE CASCADE
);
